### ISSUE TITLE
Errors while Compiling fakeroot

### ISSUE THREAD

**Issue by cyberbloke** [mikroskeem/fakeroot#1]
OS:  Linux Mint
Kernel: 5.4.0-110-generic

Getting the following errors while compiling:

In file included from libfakeroot.c:225:
wrapped.h:126:27: error: unknown type name ‘cap_user_header_t’
  126 | extern int (*next_capset)(cap_user_header_t hdrp, const cap_user_data_t datap);
      |                           ^~~~~~~~~~~~~~~~~
wrapped.h:126:57: error: unknown type name ‘cap_user_data_t’
  126 | extern int (*next_capset)(cap_user_header_t hdrp, const cap_user_data_t datap);
      |                                                         ^~~~~~~~~~~~~~~
In file included from libfakeroot.c:226:
wraptmpf.h:378:17: error: unknown type name ‘cap_user_header_t’
  378 | int tmp_capset (cap_user_header_t hdrp, const cap_user_data_t datap){
      |                 ^~~~~~~~~~~~~~~~~
wraptmpf.h:378:47: error: unknown type name ‘cap_user_data_t’
  378 | int tmp_capset (cap_user_header_t hdrp, const cap_user_data_t datap){
      |                                               ^~~~~~~~~~~~~~~
In file included from libfakeroot.c:227:
wrapdef.h:126:20: error: unknown type name ‘cap_user_header_t’
  126 | int (*next_capset)(cap_user_header_t hdrp, const cap_user_data_t datap)=tmp_capset;
      |                    ^~~~~~~~~~~~~~~~~
wrapdef.h:126:50: error: unknown type name ‘cap_user_data_t’
  126 | int (*next_capset)(cap_user_header_t hdrp, const cap_user_data_t datap)=tmp_capset;
      |                                                  ^~~~~~~~~~~~~~~
In file included from libfakeroot.c:228:
wrapstruct.h:127:14: error: ‘next_capset’ undeclared here (not in a function); did you mean ‘next_wrap_st’?
  127 |   {(void(*))&next_capset, "capset"},
      |              ^~~~~~~~~~~
      |              next_wrap_st
In file included from communicate.h:19,
                 from libfakeroot.c:60:
config.h:332:20: error: conflicting types for ‘mknod’
  332 | #define WRAP_MKNOD mknod
      |                    ^~~~~
libfakeroot.c:1049:5: note: in expansion of macro ‘WRAP_MKNOD’
 1049 | int WRAP_MKNOD MKNOD_ARG(int ver UNUSED,
      |     ^~~~~~~~~~
In file included from /usr/include/features.h:461,
                 from communicate.h:45,
                 from libfakeroot.c:60:
/usr/include/x86_64-linux-gnu/sys/stat.h:483:1: note: previous definition of ‘mknod’ was here
  483 | __NTH (mknod (const char *__path, __mode_t __mode, __dev_t __dev))
      | ^~~~~
In file included from communicate.h:19,
                 from libfakeroot.c:60:
config.h:338:22: error: conflicting types for ‘mknodat’
  338 | #define WRAP_MKNODAT mknodat
      |                      ^~~~~~~
libfakeroot.c:1086:5: note: in expansion of macro ‘WRAP_MKNODAT’
 1086 | int WRAP_MKNODAT MKNODAT_ARG(int ver UNUSED,
      |     ^~~~~~~~~~~~
In file included from /usr/include/features.h:461,
                 from communicate.h:45,
                 from libfakeroot.c:60:
/usr/include/x86_64-linux-gnu/sys/stat.h:491:1: note: previous definition of ‘mknodat’ was here
  491 | __NTH (mknodat (int __fd, const char *__path, __mode_t __mode,
      | ^~~~~
libfakeroot.c:1569:12: error: unknown type name ‘cap_user_header_t’
 1569 | int capset(cap_user_header_t hdrp, const cap_user_data_t datap)
      |            ^~~~~~~~~~~~~~~~~
libfakeroot.c:1569:42: error: unknown type name ‘cap_user_data_t’
 1569 | int capset(cap_user_header_t hdrp, const cap_user_data_t datap)
      |                                          ^~~~~~~~~~~~~~~
libfakeroot.c: In function ‘fts_read’:
![Screenshot from 2022-05-20 15-17-16](https://user-images.githubusercontent.com/6697262/169596899-faa937e7-f638-4936-a4bc-6b523b275b66.png)

**Comment by mikroskeem** [comment]
This repository is probably not the one you are looking for. See https://salsa.debian.org/clint/fakeroot or look into your distribution provided sources instead.
